name: build

on: [push, pull_request]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1

    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug lint

    - uses: actions/upload-artifact@v4
      with:
        name: debug-apks
        path: app/build/outputs/apk/debug/*.apk

    - uses: yutailang0119/action-android-lint@v3
      with:
        report-path: app/build/reports/lint-results-debug.xml
      continue-on-error: false

    - uses: marvinpinto/action-automatic-releases@latest
      if: github.ref == 'refs/heads/main'
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "debug"
        prerelease: true
        title: "${{ github.sha }}"
        files: |
          app/build/outputs/apk/debug/app-armeabi-v7a-debug.apk
          app/build/outputs/apk/debug/app-x86-debug.apk
          app/build/outputs/apk/debug/app-arm64-v8a-debug.apk
          app/build/outputs/apk/debug/app-x86_64-debug.apk
